# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10x2eFUv518i5GUzXvo8mQen3c4evOA3T
"""

# 📦 Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, classification_report

# 📥 Load dataset
df = pd.read_csv('Mobiles_Dataset_2025.csv', encoding='latin1')
print("📌 Initial Dataset:")
print(df.head())  # See the first few rows of raw data

# 🧹 Step 1: Drop duplicates + fill missing values (forward fill)
df.drop_duplicates(inplace=True)
df.ffill(inplace=True)

# 🔧 Step 2: Clean 'RAM' and 'Battery Capacity' columns
df['RAM'] = df['RAM'].astype(str).str.extract('(\d+\.?\d*)').astype(float)
df['Battery Capacity'] = df['Battery Capacity'].astype(str).str.replace(',', '').str.extract('(\d+\.?\d*)').astype(float)

# 💸 Step 3: Clean 'Launched Price (India)' by removing ₹, commas, etc.
df['Launched Price (India)'] = (
    df['Launched Price (India)']
    .astype(str)
    .str.replace('₹', '')
    .str.replace('INR', '')
    .str.replace(',', '')
    .str.extract('(\d+\.?\d*)')[0]
    .astype(float)
)

# 📱 Step 4: Clean 'Screen Size'
df['Screen Size'] = df['Screen Size'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# 🤳 Step 5: Clean 'Front Camera'
df['Front Camera'] = df['Front Camera'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# 📸 Step 6: Clean 'Back Camera' (extract max MP if multiple lenses given)
def extract_max_camera(value):
    if isinstance(value, str):
        nums = [float(n) for n in re.findall(r'\d+\.?\d*', value)]
        return max(nums) if nums else None
    return value

df['Back Camera'] = df['Back Camera'].apply(extract_max_camera)

# 🌍 Step 7: Clean other international price columns
price_cols = [
    'Launched Price (Pakistan)', 'Launched Price (China)',
    'Launched Price (USA)', 'Launched Price (Dubai)'
]

for col in price_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^\d\.]', '', regex=True)
        .str.extract('(\d+\.?\d*)')[0]
        .astype(float)
    )

# 🏷️ Step 8: Label encode the 'Company Name'
label = LabelEncoder()
df['brand_encoded'] = label.fit_transform(df['Company Name'].astype(str))

# 🧽 Step 9: Filter out mobiles with RAM > 12GB (keeping analysis practical)
df = df[df['RAM'] <= 12]

# 👀 Check cleaned data
print("\n📌 Cleaned Dataset Preview:")
print(df.head())

# 📊 Step 10: Scale selected numeric columns (for modeling later)
scaler = StandardScaler()
scale_cols = ['RAM', 'Screen Size', 'Battery Capacity', 'Launched Price (India)']
df_scaled = df.copy()
df_scaled[scale_cols] = pd.DataFrame(scaler.fit_transform(df[scale_cols]), columns=scale_cols)

# 🧠 Step 11: EDA — Customer Demand Based on RAM

# Round RAM to nearest GB for grouping
df['RAM_Rounded'] = df['RAM'].round()

# Count number of models for each RAM size
ram_counts = df['RAM_Rounded'].value_counts().sort_index()

# 📈 Step 12: Plotting the demand using seaborn
sns.set(style="whitegrid", palette="pastel")
plt.figure(figsize=(10, 6))
sns.barplot(x=ram_counts.index, y=ram_counts.values, palette="Blues_d")

# 🎨 Final plot styling
plt.title("Customer Demand Based on RAM (GB)", fontsize=16)
plt.xlabel("RAM (GB)", fontsize=14)
plt.ylabel("Number of Mobile Models", fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Step 1: Round RAM for clarity
df['RAM_Rounded'] = df['RAM'].round()

# Step 2: Label RAM > 8 as "Outlier"
df['RAM_Category'] = df['RAM'].apply(lambda x: str(int(x)) if x <= 8 else 'Outlier (>8 GB)')

# Step 3: Count models per category
ram_counts = df['RAM_Category'].value_counts().sort_index()

# Step 4: Plot
plt.figure(figsize=(10, 6))
colors = sns.color_palette("coolwarm", len(ram_counts))

sns.barplot(x=ram_counts.index, y=ram_counts.values, palette=colors)

# Make it sexy
plt.title("📱 Customer Demand Based on RAM (Including Outliers)", fontsize=18, weight='bold')
plt.xlabel("RAM Category", fontsize=14)
plt.ylabel("Number of Mobile Models", fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set Seaborn style
sns.set(style="whitegrid")

plt.figure(figsize=(12, 7))

# Ensure RAM is numeric (extract numeric part)
df['RAM'] = df['RAM'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

# Plot the average RAM over launch years with the original values
sns.lineplot(data=df, x="Launched Year", y="RAM", estimator='mean', ci=None, marker='o',
             color='teal', linewidth=2, markersize=8, markerfacecolor='red', markeredgewidth=2)

# Title and labels with custom fonts
plt.title("Average RAM Over Launch Years", fontsize=18, fontweight='bold', color='darkblue')
plt.xlabel("Launch Year", fontsize=15, fontweight='bold', color='black')
plt.ylabel("Average RAM (GB)", fontsize=15, fontweight='bold', color='black')

# Customize ticks
plt.xticks(fontsize=12, rotation=45, ha='right')
plt.yticks(fontsize=12)

# Show a clean grid
plt.grid(True, linestyle='--', alpha=0.7)

# Tight layout for better fitting
plt.tight_layout()

# Show plot
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re

# Load the dataset
df = pd.read_csv('Mobiles_Dataset_2025.csv', encoding='latin1')

# Clean 'Launched Price (India)' by removing symbols and converting to float
df['Launched Price (India)'] = (
    df['Launched Price (India)']
    .astype(str)
    .str.replace('₹', '', regex=True)  # Remove ₹ symbol
    .str.replace(',', '', regex=True)  # Remove commas
    .str.extract(r'(\d+\.?\d*)')[0]   # Extract numeric values
    .astype(float)
)

# Round the 'RAM', 'Battery Capacity', 'Screen Size', 'Launched Price (India)' to 1 decimal place for neatness
df['RAM'] = df['RAM'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float).round(1)
df['Battery Capacity'] = df['Battery Capacity'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float).round(1)
df['Screen Size'] = df['Screen Size'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float).round(1)

# Remove any rows where 'Launched Price (India)' is NaN
df = df.dropna(subset=['Launched Price (India)'])

# Function to detect outliers using IQR method
def detect_outliers(df, feature):
    Q1 = df[feature].quantile(0.25)
    Q3 = df[feature].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[feature] < lower_bound) | (df[feature] > upper_bound)]

# Detect outliers for RAM and Price
outliers_ram = detect_outliers(df, 'RAM')
outliers_price = detect_outliers(df, 'Launched Price (India)')

# EDA: Price vs. RAM (Highlighting Outliers)
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="RAM", y="Launched Price (India)", marker='o', label='Normal', color='blue')
sns.scatterplot(data=outliers_ram, x="RAM", y="Launched Price (India)", marker='o', label='Outliers', color='red', s=100)
plt.title("Price vs. RAM (Outliers Highlighted)", fontsize=16)
plt.xlabel("RAM (GB)", fontsize=14)
plt.ylabel("Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend()
plt.tight_layout()
plt.show()

# EDA: Price Distribution (Histogram) with Outliers
plt.figure(figsize=(10, 6))
sns.histplot(df['Launched Price (India)'], bins=30, kde=True, color='blue', label='Normal')
sns.histplot(outliers_price['Launched Price (India)'], bins=30, kde=True, color='red', label='Outliers')
plt.title("Price Distribution (Outliers Highlighted)", fontsize=16)
plt.xlabel("Price (₹)", fontsize=14)
plt.ylabel("Frequency", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend()
plt.tight_layout()
plt.show()

# EDA: Launch Year vs. Price (Average Price by Year) with Outliers
plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x="Launched Year", y="Launched Price (India)", estimator='mean', ci=None, marker='o', label='Average Price')
sns.scatterplot(data=outliers_price, x="Launched Year", y="Launched Price (India)", color='red', label='Outliers', s=100)
plt.title("Average Price Over Launch Years (Outliers Highlighted)", fontsize=16)
plt.xlabel("Launch Year", fontsize=14)
plt.ylabel("Average Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.regplot(data=df, x="RAM", y="Launched Price (India)", scatter=True, line_kws={"color": "green"})
plt.title("Price vs. RAM with Trendline", fontsize=16)
plt.xlabel("RAM (GB)", fontsize=14)
plt.ylabel("Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='Launched Year', y='Launched Price (India)', data=df)
plt.title("Price Distribution by Launch Year")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sns.pairplot(df[['RAM', 'Battery Capacity', 'Screen Size', 'Launched Price (India)']])
plt.suptitle("Pair Plot of Key Features", y=1.02)
plt.tight_layout()
plt.show()

# Select only numeric columns for correlation calculation
numeric_df = df.select_dtypes(include=[np.number])

# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()

# Plot the heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(x='Launched Year', y='Launched Price (India)', data=df, estimator='mean', ci=None, marker='o')
plt.title("Average Price Over Years")
plt.xlabel("Launch Year")
plt.ylabel("Average Price (₹)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="Screen Size", y="Launched Price (India)", color='blue')
plt.title("Price vs. Screen Size")
plt.xlabel("Screen Size (Inches)")
plt.ylabel("Price (₹)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(x='Company Name', data=df)
plt.xticks(rotation=90)
plt.title("Distribution of Brands")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.regplot(data=df, x="Battery Capacity", y="Launched Price (India)", scatter=True, line_kws={"color": "orange"})
plt.title("Price vs. Battery Capacity with Trendline", fontsize=16)
plt.xlabel("Battery Capacity (mAh)", fontsize=14)
plt.ylabel("Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.regplot(data=df, x="Screen Size", y="Launched Price (India)", scatter=True, line_kws={"color": "blue"})
plt.title("Price vs. Screen Size with Trendline", fontsize=16)
plt.xlabel("Screen Size (inches)", fontsize=14)
plt.ylabel("Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x="Launched Year", y="Launched Price (India)", estimator='mean', ci=None, marker='o', color='purple')
plt.title("Average Price Over Launch Years", fontsize=16)
plt.xlabel("Launch Year", fontsize=14)
plt.ylabel("Average Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(df['Launched Price (India)'], shade=True, color="blue")
plt.title("KDE Plot of Price Distribution")
plt.xlabel("Price (₹)")
plt.ylabel("Density")
plt.tight_layout()
plt.show()

sns.pairplot(df[['Launched Price (India)', 'RAM', 'Battery Capacity', 'Screen Size']])
plt.suptitle("Pair Plot of Price vs. Multiple Features", fontsize=16)
plt.tight_layout()
plt.show()

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(df['RAM'], df['Battery Capacity'], df['Launched Price (India)'], color='green')

ax.set_xlabel('RAM (GB)')
ax.set_ylabel('Battery Capacity (mAh)')
ax.set_zlabel('Price (₹)')
ax.set_title("3D Plot: Price vs. RAM and Battery Capacity")

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x="Screen Size", y="Launched Price (India)", color='red')
plt.title("Price vs. Screen Size", fontsize=16)
plt.xlabel("Screen Size (inches)", fontsize=14)
plt.ylabel("Price (₹)", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()



# Launched Price vs Battery Capacity by Brand
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='Battery Capacity', y='Launched Price (India)', hue='Company Name', palette='Set2')
plt.title('Launched Price vs Battery Capacity', fontsize=16)
plt.xlabel('Battery Capacity (mAh)', fontsize=12)
plt.ylabel('Price in ₹', fontsize=12)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Launched Price vs Screen Size by Brand
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='Screen Size', y='Launched Price (India)', hue='Company Name', palette='Set2')
plt.title('Launched Price vs Screen Size', fontsize=16)
plt.xlabel('Screen Size (inches)', fontsize=12)
plt.ylabel('Price in ₹', fontsize=12)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Price vs RAM (with color-coded brands)
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='RAM', y='Launched Price (India)', hue='Company Name', palette='cool')
plt.title('Price vs RAM (GB)', fontsize=16)
plt.xlabel('RAM (GB)', fontsize=12)
plt.ylabel('Price in ₹', fontsize=12)
plt.show()

# Price Distribution by Brand (Violin Plot)
plt.figure(figsize=(12,6))
sns.violinplot(data=df, x='Company Name', y='Launched Price (India)', palette='pastel')
plt.title("💸 Price Distribution by Brand", fontsize=16)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

from sklearn.cluster import KMeans

# Let's apply KMeans to cluster on RAM, Battery Capacity, and Screen Size
X = df[['RAM', 'Battery Capacity', 'Screen Size']].dropna()
kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(X)

# Plotting clusters
plt.figure(figsize=(10, 6))
sns.scatterplot(x='RAM', y='Launched Price (India)', hue='Cluster', data=df, palette='viridis')
plt.title("K-Means Clustering (RAM vs Price)")
plt.xlabel("RAM (GB)")
plt.ylabel("Price (₹)")
plt.tight_layout()
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Calculate correlation matrix
corr_matrix = df.corr(numeric_only=True).round(2)  # rounding for cleaner view

# Set the figure size
plt.figure(figsize=(12, 8))

# Create heatmap
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5, square=True, fmt='.2f')

# Add title
plt.title('Correlation Heatmap of Mobile Features', fontsize=16)

# Show the plot
plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Let's predict 'Launched Price (India)' based on features like 'RAM'
X = df[['RAM', 'Battery Capacity', 'Screen Size']]  # Features
y = df['Launched Price (India)']  # Target variable (Price)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Linear Regression model
model = LinearRegression()

# Fit the model with training data
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R² Score: {r2}")

# Prepare features (X) and target (y)
X = df[['RAM', 'Battery Capacity', 'Screen Size']]  # Multiple features
y = df['Launched Price (India)']  # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Calculate metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R² Score: {r2}")

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue')
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linewidth=2)
plt.title("Actual vs Predicted Price", fontsize=16)
plt.xlabel("Actual Price (₹)", fontsize=14)
plt.ylabel("Predicted Price (₹)", fontsize=14)
plt.tight_layout()
plt.show()

